<?php

defined('_JEXEC') or die('Restricted access');

JToolBarHelper::title(JText::_('Add user Frontend'), 'generic.png');

JToolBarHelper::preferences('com_adduserfrontend');

?>

<!-- Default administrator message -->

<div style="background-color:#FC0; float:right; padding:2px;"><strong>Click on the "Options" button to edit your settings!</strong></div>
<h2>Did you just install AUF?</h2>
<p>If you just installed this component you need to set it up properly. </p>
<p><strong>1. </strong>Make a link to the component in one of your menu's</p>
<p><strong>2.</strong> Now you need to configure the component. You can set the global configuration here by clicking on the "Options Button".</p>

<p><em>You can also configure the component at the menu-item in the menumanager. This will give you the possibility to run multiple instances of the component with different settings. <br />
This can come in handy if you want to add users to multiple usergroups. (Make a menu called 'Add user' and add multiple links to AUF like 'Add registered', 'Add author' or 'Add editor'. Offcourse you should also configure each menulink to AUF differently for this to work.)</em></p>



<p><em><strong>How can i define these settings?<br />
</strong>When making the link in the menu manager you will see a tab called &quot;Add user frontend&quot;.</em><br />
<em>In this tab you will see the component settings for that menu-item only. These settings override the global component settings. You can choose a different usergroup for each menu link to AUF. </em></p>
<h2>How to configure the component?</h2>
<p>Lets have a look at the options.</p>
<p><strong>1. Mode<br />
</strong>Add user to Joomla or to Joomla and Community Builder. (You should offcourse only use that last option when you have that component installed.)</p>
<p><strong>2. Namemode<br />
</strong>Would you like to have one inputfield for the name on you form? Or do you want to use 2 fields firstname and lastname.</p>
<p><strong>3. Username<br />
</strong>How should usernames be created? Should they be autogenerated, selfchosen or would you like to use the emailaddress as username.</p>
<p><strong>4. Check Username<br />
</strong>When trying to add a user the system will check for double usernames. If the chosen username exists already the username can be automatically renamed by adding a number to the username or the user can be redirected with a message.</p>
<p><strong>5. Check email<br />
</strong>Do you want to check for existing emailaddresses? You can also choose to ignore  double emailaddresses.</p>
<p><strong>6. Choose password<br />
</strong>Do you want the password to be autogenerated or chosen manually?</p>
<p><strong>7. Choose email address<br />
</strong>Almost nobody will need this. But you can also choose NOT display the email input field and autogenerate (fake) emailadress when adding a user. </p>
<p><strong>8. Email notification<br />
</strong>Do you want to sent a notification email to the user you just added containing his login data?</p>
<p><strong>8. Admin email notification<br />
</strong>Do you want to sent a notification email to the Administrator of the website when a user is added?<strong> (Will be send to the 'sent from' email in the global configuration of Joomla)</strong></p>
<p><strong>9. Usertype mode<br />
</strong>Where do you want to choose the usertype for the user you are adding? In the frontend on the form? Or in the backend?<strong> (If you choose FRONTEND you can NOT use fields 10, 11 and 12)</strong></p>
<p><strong>10. Hide standard usergroups<br />
</strong>
This option hides all default usergroups (registered, author, ...) from  the user type selectbox on the add user frontend form.<strong> (Should only be used when 'Usertype mode'(9) is set to 'Frontend'.)</strong></p>
<p><strong>11. Usertype<br />
</strong>Which type of user should be added trough the add user frontend form?  <strong>(Should only be used when 'Usertype mode'(9) is set to 'Backend'.)</strong></p>
<p><strong>12. Custom Groups<br />
</strong>
Enter the ID of the usergroup to which you want to add the new user.<strong> (Should only be used when 'Usertype mode'(9) is set to 'Backend' and  'Usertype'(11) is set to 'Custom Group'.)</strong><br />
<strong>BE CAREFULL WHEN YOU CHOOSE USERTYPES WITH A LOT OF PERMISSIONS! </strong>
<h2>If you choose the usergroup from the frontend:</h2>
<p>If you set up AUF to be able choose a usergroup from the frontend you can not control  exactly which usergroups will be displayed in the selectbox of usergroups on the  form. The selectbox will simply display all usergroups available that have less rights then the users who is about to add a new user. (Authors can add registered members. Editors can add authors and so on...)
<p>If you dont want this you can make  a menu called 'Add user' and add multiple links to AUF like 'Add registered', 'Add author' or 'Add editor'. Offcourse you should also configure each menulink to AUF differently for this to work as described above.
<p></p>
